name: Azure Web App

trigger:
  branches:
    include:
      - main

variables:
  GITHUB_TOKEN: $(GITHUB_TOKEN)

jobs:
- job: build_and_deploy
  pool: pool-euw-ado-agent

  steps:
  - script: |
      echo "Checking for sudo..."
      if command -v sudo > /dev/null; then
        echo "sudo is available"
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install -y python3.9 python3.9-venv python3.9-dev
      else
        echo "sudo is not available"
        apt-get update
        apt-get install -y software-properties-common
        add-apt-repository -y ppa:deadsnakes/ppa
        apt-get update
        apt-get install -y python3.9 python3.9-venv python3.9-dev
      fi
      echo "Creating virtual environment..."
      python3.9 -m venv venv
      echo "Activating virtual environment..."
      source venv/bin/activate
      echo "Upgrading pip..."
      python -m pip install --upgrade pip
      echo "Installing dependencies..."
      pip install -r requirements.txt
    displayName: 'Install Python 3.9 and dependencies'
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)

  - script: |
      echo "Running tests..."
      source venv/bin/activate
      pytest
    displayName: 'Run tests'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - task: AzureWebApp@1
    inputs:
      appType: 'webApp'
      azureSubscription: 'MyAzureServiceConnection'
      appName: 'app-euw-ado-agent'
      package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

