trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10.12'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'MyAzureServiceConnection'  # Використовуємо існуюче з'єднання
    appName: 'drycelaudiobot'
    package: '$(Build.ArtifactStagingDirectory)/package.zip'
  displayName: 'Deploy to Azure Web App'

