name: Azure Web App

trigger:
  branches:
    include:
      - main

jobs:
- job: build_and_deploy  # Виправлене ім'я завдання
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10.12'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pytest
    displayName: 'Run tests'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'MyAzureServiceConnection'
      appName: 'drycelaudiobot'
      package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

