name: Azure Web App

trigger:
  branches:
    include:
      - main

variables:
  GITHUB_TOKEN: $(GITHUB_TOKEN)

jobs:
- job: build_and_deploy
  pool: pool-euw-ado-agent

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pytest
    displayName: 'Run tests'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - task: AzureWebApp@1
    inputs:
      appType: 'webApp'
      azureSubscription: 'MyAzureServiceConnection'
      appName: 'app-euw-ado-agent'
      package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

