<<<<<<< HEAD
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
=======
name: Azure Web App

on:
  push:
    branches:
      - main
>>>>>>> f1ecfdc5c944245a844794505f7bb5d053f9c447

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10.12'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

<<<<<<< HEAD
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AZURE_CREDENTIALS'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az webapp deployment source config-zip \
        --resource-group YOUR_RESOURCE_GROUP \
        --name drycelaudiobot \
        --src ./$(Build.ArtifactStagingDirectory)/package.zip
  displayName: 'Deploy to Azure Web App'

